apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sj5099kvf-nodejs 
  janus-idp.io/tekton: sj5099kvf-nodejs
  backstage.io/kubernetes-id: sj5099kvf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sj5099kvf-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  