apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sj5099kvf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sj5099kvf-nodejs 
  name: sj5099kvf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sj5099kvf-nodejs 
